"""add_queues_table

Revision ID: 7e7c2334af7e
Revises: d2bca884508a
Create Date: 2026-01-17 19:02:45.416440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7c2334af7e'
down_revision: Union[str, None] = 'd2bca884508a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('queue_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('spatial_markers', sa.Column('queue_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'spatial_markers', 'queues', ['queue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spatial_markers', type_='foreignkey')
    op.drop_column('spatial_markers', 'queue_id')
    op.drop_table('queues')
    # ### end Alembic commands ###
