"""add_is_admin_to_users

Revision ID: c818b1b5faeb
Revises: 7e7c2334af7e
Create Date: 2026-01-17 19:10:57.084949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c818b1b5faeb'
down_revision: Union[str, None] = '7e7c2334af7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column with server default first (for existing rows)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # Remove server default (new rows will use Python default)
    op.alter_column('users', 'is_admin', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
