"""initial_schema

Revision ID: d2bca884508a
Revises: 
Create Date: 2026-01-17 18:56:14.339796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2bca884508a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_updates', sa.Column('club_id', sa.UUID(), nullable=False))
    op.add_column('parsed_updates', sa.Column('author_name', sa.String(length=100), nullable=True))
    op.add_column('parsed_updates', sa.Column('parsed_wait_minutes', sa.Integer(), nullable=True))
    op.add_column('parsed_updates', sa.Column('parsed_queue_length', sa.String(length=50), nullable=True))
    op.add_column('parsed_updates', sa.Column('parsed_spatial_marker', sa.String(length=100), nullable=True))
    op.add_column('parsed_updates', sa.Column('source_timestamp', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'parsed_updates', 'clubs', ['club_id'], ['id'])
    op.drop_column('parsed_updates', 'estimated_wait_minutes')
    op.drop_column('parsed_updates', 'spatial_marker')
    op.drop_column('parsed_updates', 'posted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_updates', sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('parsed_updates', sa.Column('spatial_marker', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('parsed_updates', sa.Column('estimated_wait_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parsed_updates', type_='foreignkey')
    op.drop_column('parsed_updates', 'source_timestamp')
    op.drop_column('parsed_updates', 'parsed_spatial_marker')
    op.drop_column('parsed_updates', 'parsed_queue_length')
    op.drop_column('parsed_updates', 'parsed_wait_minutes')
    op.drop_column('parsed_updates', 'author_name')
    op.drop_column('parsed_updates', 'club_id')
    # ### end Alembic commands ###
